### ISSUE TITLE
Headlines not sentence split - possibly intentional?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_Arabic#3]
There are several cases where text has a period in the middle of the sentence.  One of my Arabic speaking labmates identified those sentences as headlines.  On account of that, it may very well be intentional to not split them, but it is somewhat confusing.

```
# newpar id = xinhua.20030509.0162:p4
# sent_id = xinhua.20030509.0162:p4u1
# text = واضاف " ان كل من يتصور انه يعرف المدة التى سيستغرقها هذا الامر ، انما يخدع نفسه . انه امر غير معروف ".

# newdoc id = alhayat.20011206.0109
# newpar id = alhayat.20011206.0109:p1
# sent_id = alhayat.20011206.0109:p1u1
# text = الانتهاء من المواصفات القياسية للسلع المتبادلة الاسبوع المقبل . الصادرات المصرية الى العراق 628،1 بليون دولار في 01 شهور

# newdoc id = alhayat.20011117.0097
# newpar id = alhayat.20011117.0097:p1
# sent_id = alhayat.20011117.0097:p1u1
# text = وقعت اتفاقاً للتعاون المالي مع المانيا بقيمة 227 مليون مارك . مصر تتوقع انخفاضاً في حجم المعونات
```

There are plenty of others I can dig up.  Is this intended?  Thanks!

**Comment by otakar-smrz** [comment]
Hi, I am the former leader of the PADT treebank. In our annotations, we were working with data as originally available in the source corpora, and that was mostly as paragraphs rather than sentences. Our annotations marked punctuation on the morphological level as well as sentence boundaries on the syntactic level. I do not follow Universal Dependencies in that detail, but I believe sentence boundaries should be possible to identify.
Note that in Arabic texts, sentences tend to be connected with the <wa-> "and" conjunction instead of <.> more often than one would expect and observe in English, for instance.

**Comment by AngledLuffa** [comment]
The sentence boundaries are identifiable in the conllu files, certainly.
However, I was asking whether the sentences here should be further
separated, or whether the current headlines are meant to be kept together
as one piece.

**Comment by dan-zeman** [comment]
When converting the original PADT annotation to Universal Dependencies, I kept the original units as "sentences" in UD. That is, the segment covered by one tree in PADT is also one tree in UD_Arabic-PADT.

Splitting would require 1. identifying the internal sentence boundary; 2. making sure that no dependency relation crosses the sentence boundary; 3. deciding where to re-attach dependents whose incoming dependency violates 2. There are no plans to do this, however.

**Comment by AngledLuffa** [comment]
Thanks for looking into that.  Is it the type of thing where you would be happy to merge a pull request which addressed each of those three issues, or would you prefer to keep things with the same sentence structure as the original PADT dataset?

**Comment by dan-zeman** [comment]
I would prefer to keep the data parallel to the original treebank. Any changes that we do in the UD version are actually done in the conversion procedure, which is then re-run.

**Comment by AngledLuffa** [comment]
That seems reasonable.  Is the underlying dataset still being maintained?  I found this, but it hasn't been touched in 10 years:

http://ufal.mff.cuni.cz/padt/PADT_1.0/docs/index.html
http://padt-online.blogspot.com/

If no further updates are planned, it may not be possible to fix annotation errors - if we consider this an error - in the original treebank.

**Comment by dan-zeman** [comment]
My understanding is that the underlying dataset is somewhat larger and newer than PADT 1.0. But it is currently not actively curated.
